### ISSUE TITLE
Looking for Windows 11 ARM64 driver.

### ISSUE THREAD

**Issue by dwadi** [rtlsdrblog/rtl-sdr-blog#15]
Hi,
I am looking for ARM64 driver, I am using Windows 11 ARM in VM (Parallels) on my MacBook Air with M1 SoC, there is no way to install driver from Zadig from SDR# package :(.

**Comment by rtlsdrblog** [comment]
The rtl-sdr drivers will probably compile fine, but the problem is that Zadig does not support ARM64 on Windows. So not really anything to do with the rtl-sdr drivers themselves unfortunately.
