### ISSUE TITLE
[invalid option -- 'n'] - rtl_tcp

### ISSUE THREAD

**Issue by sp3wxh** [rtlsdrblog/rtl-sdr-blog#17]
Hi. 

I do not know why? There is a '-n' option in help.

![Zrzut ekranu 2023-05-10 o 15 23 00](https://github.com/rtlsdrblog/rtl-sdr-blog/assets/26287912/bf2beea0-3e5f-4bd2-b7ae-b3842a0548d9)

**Comment by rtlsdrblog** [comment]
Will be removed in an upcoming update.
