### ISSUE TITLE
V3 bias-t & rtl_tcp

### ISSUE THREAD

**Issue by sysrun** [rtlsdrblog/rtl-sdr-blog#2]
Hi,

just ran into a problem:

- Enable bias-t: rtl_biast -b1 (checked voltage with multimeter)
- run rtl_tcp
**bias-t will be disabled**

Workaround: enable bias-t with rtl_eeprom

Is this the expected behaviour?

**Comment by rtlsdrblog** [comment]
rtl_tcp makes use of the -T flag for enabling the bias tee (implementation from the Osmocom drivers), so if that flag isn't set the bias tee will turn off, unless you force the bias tee with rtl_eeprom of course.
