### ISSUE TITLE
RTL-SDR-BLOG Windows Release V1.1 and 1.2 have some small lags issues in SDR# with AMD CPUs

### ISSUE THREAD

**Issue by MELERIX** [rtlsdrblog/rtl-sdr-blog#20]
RTL-SDR-BLOG Windows Release V1.1 have some small lags issues in SDR#, for example when you move the Gain RF sometimes the changes are not applied instantly or sometimes when you change frequencies fastly the spectrum does not change instantly.

**Comment by rtlsdrblog** [comment]
Is this only with the blog driver, or does it happen with the standard osmocom drivers too?

**Comment by rtlsdrblog** [comment]
What PC, OS and specs do you have? I don't see this issue at all on any PC I have unfortunately.

**Comment by rtlsdrblog** [comment]
I wonder if it's something to do with newer versions of libusb and because keenerds code is very old, and built against an ancient version of libusb.

Can you try with this rtlsdr.dll? I compiled this one with v1.0.20 of libusb which should be around the version keenerd was using in 2016.

[Release.zip](https://github.com/rtlsdrblog/rtl-sdr-blog/files/12435305/Release.zip)

**Comment by rtlsdrblog** [comment]
Also if you haven't already, try updating your motherboard bios. This might be related to the AMD Ryzen issues a lot of people were having in the past.

https://www.reddit.com/r/RTLSDR/comments/u17n00/amd_ryzen_usb_problems_still_there/
https://www.reddit.com/r/Amd/comments/m2wqkf/updated_agesa_coming_for_intermittent_usb/

And try other USB ports:

https://www.reddit.com/r/SSBM/comments/hf41fw/solving_dropped_inputschoppy_movement_on_amd/

**Comment by rtlsdrblog** [comment]
How about this one? This one I copied the way Keenerd doesn't turn off the i2c repeater in set_center_freq and rtlsdr_set_tuner_gain

[Release.zip](https://github.com/rtlsdrblog/rtl-sdr-blog/files/12437329/Release.zip)

**Comment by rtlsdrblog** [comment]
Excellent, will put out a new Windows dll release next week with this fix.
