### ISSUE TITLE
rtl_tcp won't work under 11 Mhz when Direct sampling is enabled

### ISSUE THREAD

**Issue by rod2k** [rtlsdrblog/rtl-sdr-blog#21]
Scenario 1: Latest V3 RTL-SDR Dongle, Raspberry Pi 4, Raspbian Bullseye 64 Bits, MLA-30+ Antenna

Using rtl_tcp -a <ip> -D (using direct sampling) and select any freq under 12 Mhz you will see a "PLL Not Locked" message that means the tool is not able to select the frequency

Scenario 2: Latest V3 RTL-SDR Dongle, Windows 10 21H2, MLA-30+ Antenna, RTL-SDR Blog V 1.1 Binaries, same issue, "PLL Not Locked" trying to select any freq under 12 Mhz aprox

Same hardware works flawlessly with SDRSharp Rev. 1919, Zadik drivers, Windows 10 21H2, same MLA-30 Antenna using Direct Sampling, I'm able to listen any HF frequency

**Comment by rtlsdrblog** [comment]
What software are you using to connect to rtl_tcp?

I can't replicate this problem, I don't get error when tuning below 12 MHz in SDR# connected to rtl_tcp.

**Comment by rod2k** [comment]
I'm using SDRTouch for Android, connecting to my SDR in the same LAN
https://play.google.com/store/apps/details?id=marto.androsdr2&hl=es&gl=US

![image](https://github.com/rtlsdrblog/rtl-sdr-blog/assets/23507339/75b47642-ef65-4567-91b7-1ca408681999)

**Comment by rtlsdrblog** [comment]
I just tested SDR Touch and didn't get the error, but also at the same time I couldn't really get any AM output from SDRTouch. Not sure why.

When you typed rtl_tcp -a -D, did you actually type the IP address after -a? rtl_tcp -a 0.0.0.0 -D

Without the IP the -D flag might not get picked up.

**Comment by rtlsdrblog** [comment]
Looks like SDR Touch is sending a command to disable direct sampling mode for some reason. See the "Disabled direct sampling mode" line near the bottom.

Please try the latest code up now. In this new code you shouldn't even need to specific the -D flag, as it will auto-enable direct sampling when the frequency goes below 28.8 MHz.

**Comment by rod2k** [comment]
I've tested this issue with the latest version of the drivers and I can confirm you that now works good with SDRTouch

![image](https://github.com/rtlsdrblog/rtl-sdr-blog/assets/23507339/fd23b730-2fd6-4a11-bab4-0263c810ca89)
