### ISSUE TITLE
RTL-SDR-BLOG Windows Release V1.2 does not include pthreadVC2.dll

### ISSUE THREAD

**Issue by TrueBlueBlooded** [rtlsdrblog/rtl-sdr-blog#22]
Windows Release v1.2 does not include 32-bit and 64-bit pthreadVC2.dll which is needed for rtl_adsb.exe, rtl_fm.exe, and rtl_tcp.exe.

**Comment by rtlsdrblog** [comment]
Thanks, included now in the latest release https://github.com/rtlsdrblog/rtl-sdr-blog/releases/tag/V1.3
