### ISSUE TITLE
usb_open error -5

### ISSUE THREAD

**Issue by mycall** [rtlsdrblog/rtl-sdr-blog#27]
Hello, I just unpackaged my new V4 and tried out the latest Releases, but rtl_test shows some error:

Found 1 device(s):
  0:  , , SN:

Using device 0: Generic RTL2832U OEM
usb_open error -5
Failed to open rtlsdr device #0.

This happens on multiple computers.   Is my unit dead?

**Comment by MindStudioOfficial** [comment]
what was the issue?
