### ISSUE TITLE
Provide instructions for librtlsdr0 and librtlsdr-dev via Debian packages

### ISSUE THREAD

**Issue by by** [rtlsdrblog/rtl-sdr-blog#28]
Wouldn't it be better to provide instructions to build debian packages in order to have proper new versions of both librtlsdr0 and librtlsdr-dev available (which where purge prior to V4 driver installation?

**Comment by by** [comment]
P.S.: And rise the version number accordingly, so that they are not overwritten by standard packages, e.g., Debian bookworm

**Comment by rtlsdrblog** [comment]
Completed.
