### ISSUE TITLE
Install instructions wrong

### ISSUE THREAD

**Issue by happysat** [rtlsdrblog/rtl-sdr-blog#3]
Hey Guys,

Nice driver, great job!
Please change line 36 from readme:
It says:

git clone git://git.osmocom.org/rtl-sdr.git

So folks will pull the git from there and not this git.

We need this git:

git clone git://github.com/rtlsdrblog/rtl-sdr-blog.git

**Comment by rtlsdrblog** [comment]
Thanks, fixed.
