### ISSUE TITLE
Mac OS installation error in function 'rtlsdr_set_bias_tee_gpio'

### ISSUE THREAD

**Issue by Tritoni24** [rtlsdrblog/rtl-sdr-blog#30]
I've tried to install rtl-sdr software in my M1 macbook pro computer, following the instructions from README.md but this error comes up. What can I do to solve it? 
`error: call to undeclared function 'rtlsdr_set_bias_tee_gpio'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        rc = rtlsdr_set_bias_tee_gpio(priv->rtl_dev, 5, !cable_2_in);
                             ^
1 error generated.
make[2]: *** [src/CMakeFiles/rtlsdr.dir/tuner_r82xx.c.o] Error 1
make[1]: *** [src/CMakeFiles/rtlsdr.dir/all] Error 2
make: *** [all] Error 2
`

TY!

**Comment by dwadi** [comment]
Same...

**Comment by vornao** [comment]
I am experiencing the same issue.
I am using this version of clang. MacOS Sonoma, M2 pro processor.

```
Apple clang version 15.0.0 (clang-1500.0.40.1)
Target: arm64-apple-darwin23.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
No issues compiling on another linux machine with gnu gcc.

**Comment by pedroCX486** [comment]
Same here, full logs: https://github.com/pedroCX486/SDRPlusPlus/actions/runs/6366695440/job/17284640740

**Comment by martincmartin** [comment]
Same for me.

**Comment by vornao** [comment]
## I found the problem was the CLang Apple compiler that comes with the default command line tools

**Comment by vornao** [comment]
I found that the problem was clang compiler that comes with the standalone xcode command line tools. I solved using GNU gcc from homebrew. Here are the steps to make things work.

1. `brew install gcc`, install gcc via homebrew.
2. `cmake -DCMAKE_C_COMPILER=gcc-13 ../` run this from the build this to generate makefiles specifying the new gcc executable.
3. `make` (if gcc doesn't find libusb type `make LIBRARY_PATH=/opt/homebrew/Cellar/libusb/1.0.26/lib` or whatever path your `libusb` is.
4. `make install` as usual.

Enjoy!

**Comment by dwadi** [comment]
> I found that the problem was clang compiler that comes with the standalone xcode command line tools. I solved using GNU gcc from homebrew. Here are the steps to make things work.
> 
> 1. `brew install gcc`, install gcc via homebrew.
> 2. `cmake -DCMAKE_C_COMPILER=gcc-13 ../` run this from the build this to generate makefiles specifying the new gcc executable.
> 3. `make` (if gcc doesn't find libusb type `make LIBRARY_PATH=/opt/homebrew/Cellar/libusb/1.0.26/lib` or whatever path your `libusb` is.
> 4. `make install` as usual.
> 
> Enjoy!

Installed, but I have problem with SDR++ now hen I've disabled Direct Sampling for my V4 SDR++ FC itself...

**Comment by benleb** [comment]
> 3\. LIBRARY_PATH=/

thanks, works! great answer 👍

**Comment by pedroCX486** [comment]
> > I found that the problem was clang compiler that comes with the standalone xcode command line tools. I solved using GNU gcc from homebrew. Here are the steps to make things work.
> > 
> > 1. `brew install gcc`, install gcc via homebrew.
> > 2. `cmake -DCMAKE_C_COMPILER=gcc-13 ../` run this from the build this to generate makefiles specifying the new gcc executable.
> > 3. `make` (if gcc doesn't find libusb type `make LIBRARY_PATH=/opt/homebrew/Cellar/libusb/1.0.26/lib` or whatever path your `libusb` is.
> > 4. `make install` as usual.
> > 
> > Enjoy!
> 
> thanks, works! great answer 👍

Can also confirm. Got the builds on my fork working for both M1 and Intel macOS: [https://github.com/pedroCX486/SDRPlusPlus](https://github.com/pedroCX486/SDRPlusPlus)

But directly sampling seems indeed borked.

**Comment by kc9zyz** [comment]
I created #32 to resolve - but I have some software modularity concerns and would appreciate feedback.

**Comment by rd0fun** [comment]
That worked great. Thank you. I can now compile. But I can't run any of the resultant binaries.

```
 % /usr/local/bin/rtl_eeprom
dyld[87871]: Symbol not found: _rtlsdr_close
  Referenced from: <7BA311E4-0569-391E-B708-6F0CFA49BF1E> /usr/local/bin/rtl_eeprom
  Expected in:     <no uuid> unknown
zsh: abort      /usr/local/bin/rtl_eeprom
```

I receive the same for every rtl binary in /usr/local/bin/. 

Any ideas?

**Comment by rkarikari** [comment]
> That worked great. Thank you. I can now compile. But I can't run any of the resultant binaries.
> 
> ```
>  % /usr/local/bin/rtl_eeprom
> dyld[87871]: Symbol not found: _rtlsdr_close
>   Referenced from: <7BA311E4-0569-391E-B708-6F0CFA49BF1E> /usr/local/bin/rtl_eeprom
>   Expected in:     <no uuid> unknown
> zsh: abort      /usr/local/bin/rtl_eeprom
> ```
> 
> I receive the same for every rtl binary in /usr/local/bin/.
> 
> Any ideas?
 
Please proceed with caution !!!


The old drivers were installed in .....     /opt/local/bin/

be sure you have uninstalled them all .....

```
  brew uninstall rtlsdr
  sudo port uninstall rtlsdr 
```
..etc


I had to manually delete .... 

```
sudo rm  -f      /opt/local/lib/librtlsdr.dylib
sudo rm -f      /opt/local/lib/librtlsdr.a
```

Then install the new ones after compiling ...
from the build directory.....

```
sudo make install

```

the new ones are installed in ......         
 /usr/loca/ bin   etc ..


```
 la -al /usr/local/lib/librtlsdr.dylib
lrwxr-xr-x  1 root  admin    17B Oct 31 20:09 /usr/local/lib/librtlsdr.dylib -> librtlsdr.0.dylib
 
 
 ls -al  /usr/local/lib/librtlsdr.a
-rw-r--r--  1 root  admin  89248 Oct 31 20:39 /usr/local/lib/librtlsdr.a
```

I hope this helps.
Please proceed with caution !!!

**Comment by rtlsdrblog** [comment]
The implicit declaration should be fixed.

Mac users please make sure you're making with

`make LIBRARY_PATH=/usr/local/lib`
