### ISSUE TITLE
RTL_433 not working

### ISSUE THREAD

**Issue by loewal** [rtlsdrblog/rtl-sdr-blog#31]
Compiled RTL_433.
Only output is:
bitbuffer_add_bit: Warning: row count limit (50 rows) reached
bitbuffer_add_bit: Warning: row count limit (50 rows) reached
bitbuffer_add_bit: Warning: row count limit (50 rows) reached
bitbuffer_add_bit: Warning: row count limit (50 rows) reached

Tried several gain-options. This resulted in no output at all.
Using is with SDRplusplus is fine, of course also in HF.

Is this a bug?

**Comment by loewal** [comment]
Sorry, forgot to mention:
Attaching a Nesdr Smartsdr works fine on the same machine.

**Comment by krakenrf** [comment]
What OS, and did you compile and install the new RTL-SDR blog drivers, or the latest version of the Osmocom drivers?

**Comment by rtlsdrblog** [comment]
Closing due to no response.
