### ISSUE TITLE
RTLSDR issues (RTLSDR v4) on Macos

### ISSUE THREAD

**Issue by rkarikari** [rtlsdrblog/rtl-sdr-blog#34]
Hello ,
I've noticed the following issues with RTLSDR BLOG V4 ...

(current system: Monterey 12.7)

RTLSDR compiled and updated to latest version for V4 support.

V3 still works great with all software tested.

### For Blog V4,

Gqrx works (normal tuning through entire supported frequency range, no DIrect sampling required)
SDR++ works (normal tuning through entire supported frequency range, no DIrect sampling required)
SDRAngel works (normal tuning through entire supported frequency range, no DIrect sampling required) 

### The following do not work  with V4!
AIS-catcher does not work
RTL_FM does not work ....

.... with rtl_fm, found a cluster of commercial broadcast FM stations approx -30Mhz off-frequency
.... 53Mhz and above instead of ( 88 - 108 )Mhz

Any ideas how to resolve this please ?

**Comment by krakenrf** [comment]
GQRX, SDR++ and SDRAngl all bundle the drivers in their packages, and they have been updated so they will work.

For AISCatcher, I am unsure if they have updated their package.

For rtl_fm, this should work assuming you have installed the latest drivers. But instead it sounds like it is still using old drivers. Did you purge your system of any previously installed drivers?

**Comment by rkarikari** [comment]
Simply uninstalling ( brew / macports ) was not enough !
I had to manually delete some orphan files to get it to work.

Thanks.
