### ISSUE TITLE
rtl_power with confusing help text on -T (enable bias-T)

### ISSUE THREAD

**Issue by by** [rtlsdrblog/rtl-sdr-blog#40]
Some 7 years ago, commit https://github.com/rtlsdrblog/rtl-sdr-blog/commit/18bf26989c926a5db4fca29e7d859af42af1437c introduced the extremely helpful option -T for enabling bias-T to rtl_power.

The related help text states "-T enable bias-T on GPIO PIN 0 (works for rtl-sdr.com v3 dongles)", which I find confusing, as it works perfectly via USB and with the new v4 dongle.

**Comment by by** [comment]
My setup is both a RTL-SDR v3 and v4 plus a RTL-SDR ADS-B LNA with built-in bias-T support.

**Comment by rtlsdrblog** [comment]
Yes the bias tee on the V4 is exactly the same design as on the V3, so it will work fine. That text should be updated to V3/V4.

**Comment by rtlsdrblog** [comment]
Text has been updated.
