### ISSUE TITLE
Error: call to undeclared function 'rtlsdr_set_bias_tee_gpio'; ISO C99 and later do not support implicit function declarations

### ISSUE THREAD

**Issue by welly** [rtlsdrblog/rtl-sdr-blog#41]
Hi all,

Having a problem building the project on my M3 MacBook Pro. Running cmake ../ shows:

```
[17:12:08]
-- Build type not specified: defaulting to release.
-- Extracting version information from git describe...
-- Udev rules not being installed, install them with -DINSTALL_UDEV_RULES=ON
-- Building with kernel driver detaching disabled, use -DDETACH_KERNEL_DRIVER=ON to enable
-- Building with usbfs zero-copy support disabled, use -DENABLE_ZEROCOPY=ON to enable
-- Building for version: 0.6.0-115-g04a8 / 0.6git
-- Using install prefix: /usr/local
-- Configuring done (0.1s)
-- Generating done (0.0s)
-- Build files have been written to: /Users/dx-1267macbookair/dev/src/rtl-sdr-blog/build
```

However running make LIBRARY_PATH=/usr/local/lib shows:

```
[  3%] Building C object src/CMakeFiles/rtlsdr.dir/tuner_r82xx.c.o
/Users/macbook/dev/src/rtl-sdr-blog/src/tuner_r82xx.c:1186:9: error: call to undeclared function 'rtlsdr_set_bias_tee_gpio'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        rc = rtlsdr_set_bias_tee_gpio(priv->rtl_dev, 5, !cable_2_in);
                             ^
1 error generated.
make[2]: *** [src/CMakeFiles/rtlsdr.dir/tuner_r82xx.c.o] Error 1
make[1]: *** [src/CMakeFiles/rtlsdr.dir/all] Error 2
make: *** [all] Error 2

```

**Comment by erodas** [comment]
same here, Intel Mac Pro 2019:

Building C object src/CMakeFiles/rtlsdr.dir/tuner_r82xx.c.o
/Users/------/rtl-sdr-blog/src/tuner_r82xx.c:1186:9: error: call to undeclared function 'rtlsdr_set_bias_tee_gpio'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                        rc = rtlsdr_set_bias_tee_gpio(priv->rtl_dev, 5, !cable_2_in);

**Comment by jvater** [comment]
Same problem on my M1 2021 MacBookPro.

**Comment by jvater** [comment]
An `export CFLAGS=-Wno-implicit-function-declaration` before `cmake ../`  (see build-instruction for macOS on https://www.rtl-sdr.com/V4/) works for me on this error. 

Then I get the next error:
`➜  build git:(master) ✗ make LIBRARY_PATH=/usr/local/lib
[  3%] Linking C shared library librtlsdr.dylib
ld: warning: ignoring duplicate libraries: '-lusb-1.0'
ld: library 'usb-1.0' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/librtlsdr.0.6git.dylib] Error 1
make[1]: *** [src/CMakeFiles/rtlsdr.dir/all] Error 2
make: *** [all] Error 2`

libusb seems to be present, a ls -l /opt/local/lib/libusb* shows:
`➜  build git:(master) ✗ ls -l /opt/local/lib/libusb*        
-rwxr-xr-x  1 root  admin   37808 10 Nov 19:03 /opt/local/lib/libusb-0.1.4.dylib
-rwxr-xr-x  1 root  admin  159488  8 Nov 01:25 /opt/local/lib/libusb-1.0.0.dylib
-rw-r--r--  1 root  admin  194408  8 Nov 01:25 /opt/local/lib/libusb-1.0.a
lrwxr-xr-x  1 root  admin      18  8 Nov 01:25 /opt/local/lib/libusb-1.0.dylib -> libusb-1.0.0.dylib
-rw-r--r--  1 root  admin   15536 10 Nov 19:03 /opt/local/lib/libusb.a
lrwxr-xr-x  1 root  admin      18 10 Nov 19:03 /opt/local/lib/libusb.dylib -> libusb-0.1.4.dylib
-rwxr-xr-x  1 root  admin   63784  8 Nov 11:13 /opt/local/lib/libusbredirhost.1.dylib
lrwxr-xr-x  1 root  admin      23  8 Nov 11:13 /opt/local/lib/libusbredirhost.dylib -> libusbredirhost.1.dylib
-rwxr-xr-x  1 root  admin   60552  8 Nov 11:13 /opt/local/lib/libusbredirparser.1.dylib
lrwxr-xr-x  1 root  admin      25  8 Nov 11:13 /opt/local/lib/libusbredirparser.dylib -> libusbredirparser.1.dylib`

**Comment by rtlsdrblog** [comment]
Odd, something must have changed in homebrew or Xcode. I'll try get on a Mac in a few days to have a look.

**Comment by rtlsdrblog** [comment]
The implicit delcaration is fixed now.

Make sure you're making with 

`make LIBRARY_PATH=/usr/local/lib`

If that doesn't work, then you probably have custom installed libusb to another folder. so you'd need to specify that folder instead as the LIBRARY_PATH.
