### ISSUE TITLE
Rafael Micro R820T tuner - now no longer works with latest build

### ISSUE THREAD

**Issue by MiddleSiggy** [rtlsdrblog/rtl-sdr-blog#44]
I just compiled the latest build to get my RTL-SDR v4 to work, and it did.. 

But now the older SDR I had no longer can detect anything..

I followed the direction to the tee.. 

What am I doing wrong.. It seems to run, but just never detects anything:
rtl_433
rtl_433 version 23.11-54-gf88bf685 branch master at 202402112003 inputs file rtl_tcp RTL-SDR with TLS
Found Rafael Micro R820T tuner
[SDR] Using device 0: Realtek, RTL2838UHIDIR, SN: 00000001, "Generic RTL2832U OEM"
Exact sample rate is: 250000.000414 Hz
Enabled direct sampling mode, input 2
[R82XX] PLL not locked!
Disabled direct sampling mode

Thanks

**Comment by MiddleSiggy** [comment]
So I reverted back to the older driver and the dongle will pick up signals again.

Is this library exclusive to just the v4 dongle (2832)? 
or should it have also supported the R820T?

Thanks

**Comment by Mak3Stuff** [comment]
I have a similar question... I'm currently running a Radarbox ADS-b Flightbox for 1090mhz and a Flight Aware Pro for 978mhz. Both are feeding through Ultrafeeder via Docker running on an 8gb RPi 5. I want to add a V4 and play with SDR. Will this new driver kill my existing setup?

**Comment by MiddleSiggy** [comment]
It seems this is a fork..

Use this driver and compile:
git clone https://gitea.osmocom.org/sdr/rtl-sdr.git
