### ISSUE TITLE
rtl_tcp uses a full CPU core

### ISSUE THREAD

**Issue by OE4AMW** [rtlsdrblog/rtl-sdr-blog#7]
The variant of rtl_tcp using a ringbuffer performs quite well, however, it always uses 100% of a CPU (on a raspberry pi 1, pi 4, or even on my laptop with a core i7).

**Comment by danburd** [comment]
I have found the same to be the case on a Raspberry Pi 4 running Raspbian.

**Comment by rtlsdrblog** [comment]
Will be going back to the standard rtl_tcp implementation in the next update, it looks like the ring buffer patch has issues.
