### ISSUE TITLE
Forcing the Bias Tee to be Always On - not working!

### ISSUE THREAD

**Issue by T-Shilov** [rtlsdrblog/rtl-sdr-blog#9]
Hello,

I did so:

```
~$ rtl_eeprom -b y

Found 1 device(s):
  0:  Generic RTL2832U OEM

Using device 0: Generic RTL2832U OEM
Detached kernel driver
Found Rafael Micro R820T/2 tuner

Current configuration:
__________________________________________
Vendor ID:              0x0bda
Product ID:             0x2838
Manufacturer:           Realtek
Product:                RTL2838UHIDIR
Serial number:          00001006
Serial number enabled:  yes
Bias-T Always ON:       no
Direct Sampling Always ON:      no
__________________________________________

New configuration:
__________________________________________
Vendor ID:              0x0bda
Product ID:             0x2838
Manufacturer:           Realtek
Product:                RTL2838UHIDIR
Serial number:          00001006
Serial number enabled:  yes
Bias-T Always ON:       yes
Direct Sampling Always ON:      no
__________________________________________
Write new configuration to device [y/n]? y

Configuration successfully written.
Please replug the device for changes to take effect.
Reattached kernel driver
~$
```

Then turned on and turned off the dongle.
But voltages on the Bias Tee did not appear.

**Why doesn't it work ???**

**Comment by krakenrf** [comment]
You will need to run a program that uses the rtl-sdr-blog drivers first before it turns on. So 1) ensure that you have cleaned your system of prior drivers to ensure that the rtl-sdr-blog drivers are the only active ones on the system, and then 2) run any software that accesses the dongle to turn the bias tee on.

**Comment by rtlsdrblog** [comment]
You will need to run a program that uses the rtl-sdr-blog drivers first before it turns on. So 1) ensure that you have cleaned your system of prior drivers to ensure that the rtl-sdr-blog drivers are the only active ones on the system, and then 2) run any software that accesses the dongle to turn the bias tee on.

**Comment by T-Shilov** [comment]
I did it :-). Please read this correspondence: 
https://www.rtl-sdr.com/rtl-sdr-blog-v-3-dongles-user-guide/comment-page-3/#comment-210448
But when I run any SDR-application (Gqrx or OpenWebRX), it does the opposite - it turns off this voltage.

**Comment by rtlsdrblog** [comment]
I think the issue might be that GQRX and OpenWebRX are using their own drivers, which overrule the system driver and might force the bias tee GPIO off. In GQRX, can you try the device string "rtl=0,bias=1". In OpenWebRX I believe uses Soapy not the system driver, so you might need to consult this topic https://groups.io/g/openwebrx/topic/rtl_bias_tee/71911380?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,40,71911380

To test if the system driver is working, you could try running a program that definitely uses it like rtl_fm and seeing if the bias tee turns on.

It's a bit annoying, but the force bias tee hack will only work for programs that use the installed rtl-sdr-blog driver.

**Comment by T-Shilov** [comment]
I'm sorry, I don't quite understand you.
I have another second dongle, also RTL-SDR v3.
 I connect it to a regular +5 Volt power supply. And on the Bias Tee, a voltage of + 4.5 Volts immediately appears - and this voltage  after reconnecting not disappear! 
This  is excellent and correct behavior!

This voltage even appears and not disappear  when the dongle is connected to any computer without RTL drivers.

I need exactly this dongle behavior! 
Why does the first key behave differently? Why doesn't he remember this voltage +4.5V forever?

**Comment by rtlsdrblog** [comment]
You mean when connecting it to a 5V power supply, that has no data connection? Then what you're seeing is likely to simply be the random nature of the uninitialized GPIO. Without any code to init the GPIO, it will be in a random state based on the minor variances in silicon between chips.

**Comment by T-Shilov** [comment]
However, I need to have a voltage of +4.5 Volts always present on BiasTia and not depend on the presence and state of applications (Gqrx, OpenWebRX).
Is this possible?

**Comment by T-Shilov** [comment]
You even can assume that I do not have applications that control the dongle RTL.
How do I get a constant voltage of +4.5 Volt in this dongle?

**Comment by rtlsdrblog** [comment]
The bias tee is software controlled, there must be a signal sent in software to turn it on. The GPIO cannot be controlled without a software signal.

If you do not run any application software, the instead you could set a script to run rtl_biast as soon as the dongle is plugged in.
